"""users table

Revision ID: 2a74f7dcb91c
Revises: 3be6b3c9deed
Create Date: 2020-03-18 12:27:57.880824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a74f7dcb91c'
down_revision = '3be6b3c9deed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('client_name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'client_name')
    # ### end Alembic commands ###
