"""country table

Revision ID: 58c68ba38781
Revises: 2a74f7dcb91c
Create Date: 2020-03-18 19:18:49.585853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c68ba38781'
down_revision = '2a74f7dcb91c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_country_name'), 'country', ['country_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_country_country_name'), table_name='country')
    op.drop_table('country')
    # ### end Alembic commands ###
