"""city table

Revision ID: 5db6ffd695e6
Revises: 58c68ba38781
Create Date: 2020-03-18 20:00:06.474461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db6ffd695e6'
down_revision = '58c68ba38781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zip_code', sa.String(length=64), nullable=True),
    sa.Column('city_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_city_name'), 'city', ['city_name'], unique=False)
    op.create_index(op.f('ix_city_zip_code'), 'city', ['zip_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_city_zip_code'), table_name='city')
    op.drop_index(op.f('ix_city_city_name'), table_name='city')
    op.drop_table('city')
    # ### end Alembic commands ###
