"""account table

Revision ID: c1f5dda0f42f
Revises: 55898fc36a8f
Create Date: 2020-03-22 16:19:01.213264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c1f5dda0f42f"
down_revision = "55898fc36a8f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_account_name_account", table_name="account")
    op.create_index(
        op.f("ix_account_name_account"), "account", ["name_account"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_name_account"), table_name="account")
    op.create_index(
        "ix_account_name_account", "account", ["name_account"], unique=False
    )
    # ### end Alembic commands ###
