"""account table

Revision ID: c8e0aa159e60
Revises: c1f5dda0f42f
Create Date: 2020-03-23 15:51:36.036087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c8e0aa159e60"
down_revision = "c1f5dda0f42f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "balance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"],),
        sa.ForeignKeyConstraint(["client_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("balance")
    # ### end Alembic commands ###
