"""users table

Revision ID: d1d6034a5385
Revises: 77b2c39fd34f
Create Date: 2020-03-04 17:42:37.668361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d1d6034a5385"
down_revision = "77b2c39fd34f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("hashCode", sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "hashCode")
    # ### end Alembic commands ###
