"""contract table

Revision ID: f84f3343fd86
Revises: 792019c91865
Create Date: 2020-03-21 17:26:12.775665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f84f3343fd86'
down_revision = '792019c91865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=True),
    sa.Column('init_date', sa.String(length=128), nullable=True),
    sa.Column('end_date', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_fee'), 'contract', ['fee'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_fee'), table_name='contract')
    op.drop_table('contract')
    # ### end Alembic commands ###
