"""city table

Revision ID: fc4a098bc491
Revises: 5db6ffd695e6
Create Date: 2020-03-18 20:04:36.423043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4a098bc491'
down_revision = '5db6ffd695e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('countr_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'city', 'country', ['countr_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'city', type_='foreignkey')
    op.drop_column('city', 'countr_id')
    # ### end Alembic commands ###
