"""balance table

Revision ID: fc8cb5f0f910
Revises: c8e0aa159e60
Create Date: 2020-03-23 16:51:54.167968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8cb5f0f910'
down_revision = 'c8e0aa159e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_balance_balance'), 'balance', ['balance'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_balance'), table_name='balance')
    # ### end Alembic commands ###
